#HOST           TIPO            NOMBRE          USUARIO         LOOPBACK_IP         OSPF_AREA
192.168.100.1   router          CSR-ROUT1       admin           10.0.0.1            0
192.168.100.2   router          CSR-ROUT2       admin           10.0.0.2            0
192.168.100.3   router          CSR-ROUT3       admin           10.0.0.3            0
192.168.100.10  switch          SW-DIST1        admin           10.0.10.1           0
192.168.100.11  switch          SW-DIST2        admin           10.0.10.2           0
192.168.100.20  switch          SW-ACC1         admin           10.0.20.1           1
192.168.100.21  switch          SW-ACC2         admin           10.0.20.2           2
192.168.100.22  switch          SW-ACC3         admin           10.0.20.3           3
192.168.100.23  switch          SW-ACC4         admin           10.0.20.4           4