#LOOPBACK_IP         TYPE             NAME          USER                    OSPF_AREA
10.99.99.1          router          CSR-ROUT1       admin                       0
10.99.99.2          router          CSR-ROUT2       admin                       0
10.99.99.3          router          CSR-ROUT3       admin                       0
10.99.99.4          switch-l3       SW-DIST1        admin                       0
10.99.99.5          switch-l3       SW-DIST2        admin                       0
10.99.99.6          switch-l2       SW-ACC1         admin                       1
10.99.99.7          switch-l2       SW-ACC2         admin                       2
10.99.99.8          switch-l2       SW-ACC3         admin                       3
10.99.99.9          switch-l2       SW-ACC4         admin                       4