SVI_VLAN10_IP="10.10.10.253"
SVI_VLAN20_IP="10.20.20.253"
SVI_VLAN30_IP="10.30.30.253"
SVI_VLAN40_IP="10.40.40.253"
SVI_VLAN99_IP="10.99.99.253"

HSRP_PRIORITY_VLAN10="110"
HSRP_PRIORITY_VLAN20="110"
HSRP_PRIORITY_VLAN30="90"
HSRP_PRIORITY_VLAN40="90"
HSRP_PRIORITY_VLAN99="110"

STP_VLAN10="primary"
STP_VLAN20="primary"
STP_VLAN30="secondary"
STP_VLAN40="secondary"
STP_VLAN99="primary"