SVI_VLAN10_IP="10.10.10.252"
SVI_VLAN20_IP="10.20.20.252"
SVI_VLAN30_IP="10.30.30.252"
SVI_VLAN40_IP="10.40.40.252"
SVI_VLAN99_IP="10.99.99.6"

HSRP_PRIORITY_VLAN10="90"
HSRP_PRIORITY_VLAN20="90"
HSRP_PRIORITY_VLAN30="110"
HSRP_PRIORITY_VLAN40="110"
HSRP_PRIORITY_VLAN99="90"

STP_VLAN10="secondary"
STP_VLAN20="secondary"
STP_VLAN30="primary"
STP_VLAN40="primary"
STP_VLAN99="secondary"